import json
import re
import pandas as pd
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any

# ==============================================================================
# 1. CONFIGURAÇÃO: MAPAS E METADADOS
# ==============================================================================

# Mapa de Termo CSV -> Expressão SNOMED (Simples ou Composta)
USER_SNOMED_MAP = {
    "AF (Atrial Fibrillation)": "49436004", 
    "NSR (Normal Sinus Rhythm)": "426285000",
    "Noise": "251143007", 
    "Others": "10003008",   

    "activity_unknown": "261665006",
    "activity_lying": "+102538003",
    "activity_sitting_standing": "33586001+10904000",
    "activity_cycling": "54921000087109", 
    "activity_slope_up": "282489003",
    "activity_jogging": "1968006", 
    "activity_slope_down": "282495002",
    "activity_walking": "129006008",
    "activity_sitting_lying": "33586001+102538003",
    "activity_standing": "10904000",
    "activity_sitting": "33586001",

    "not_worn": "262009000",
    "body_unknown": "261665006",
    "body_lying_supine": "40199007",
    "body_lying_left": "272571008",
    "body_lying_prone": "1240000",
    "body_lying_right": "272570009",
    "body_upright": "249862003",
    "body_sitting_lying": "33586001+102538003",
    "body_standing": "10904000",
    "body_not_worn": "262009000",
    "wake": "27625002",
    "sleep": "258158006",


    "gender_M": "248153007",
    "gender_F": "248152002",
    
    "adulto_jovem": "133936004",   
    "adulto": "133936004",         
    "quase_idoso": "133936004",    
    "idoso": "105436006",         

    "peso_muito_baixo": "726527001+260362008", 
    "peso_baixo": "726527001+62482003",    
    "peso_medio": "726527001+1255665007",       
    "peso_alto": "726527001+75540009",    

    "height_baixo": "1153637007+62482003",       
    "height_medio": "1153637007+1255665007",     
    "height_alto": "1153637007+75540009",        
    "height_muito_alto": "1153637007+260360000", 

    "met_1.0": "698834005+62482003",          
    "met_1.25": "698834005+1255665007",       
    "met_acima_1.25": "698834005+75540009",       
    
    "acc_muito_baixa": "285659007+62482003",     
    "acc_baixa": "285659007+62482003",           
    "acc_moderada": "285659007+1255665007",      
    "acc_alta": "285659007+75540009"             
}

# Novo: Metadados para os "Átomos" (Conceitos base para construir os Customs)
# Isso permite que o sistema busque o nome oficial e definição de cada parte.
ATOM_METADATA = {
    "49436004": {"term": "Atrial Fibrillation", "def": "Cardiac arrhythmia characterized by disorganized atrial electrical activity."},
    "426285000": {"term": "Normal Sinus Rhythm", "def": "Normal heartbeat rhythm generated by the sinus node."},
    "285659007": {"term": "Acceleration (physical force)", "def": "Rate of change of velocity of a body."},
    "62482003":  {"term": "Low (qualifier value)", "def": "Below normal or average level."},
    "102538003": {"term": "Recumbency", "def": "The state of leaning, resting, or reclining."},
    "40199007":  {"term": "Supine body position", "def": "Lying continuously on the back."}
}

# ==============================================================================
# 2. ESTRUTURAS DE DADOS (MODELO)
# ==============================================================================

@dataclass
class AssociationRule:
    antecedents: List[str]
    consequents: List[str]
    confidence: float
    lift: float
    support: float

@dataclass
class ConceptNode:
    sctid: str                  # O ID original (pode ser 123 ou 123+456)
    fsn: str                    # Termo amigável
    is_custom: bool = False     # Flag para saber se é composto
    custom_id: str = ""         # Ex: CUST_001
    constituents: List[dict] = field(default_factory=list) # Lista das partes (basedOn)
    definition: str = ""        # Definição gerada ou buscada
    semantic_tag: str = "finding"

    def to_output_format(self):
        """Retorna o dicionário formatado conforme solicitado pelo usuário."""
        if self.is_custom:
            # Formato CUSTOM (Rico)
            formatted_based_on = [
                f"{c['id']} | {c['term']} |" for c in self.constituents
            ]
            return {
                "customSctid": self.custom_id,
                "fsn": self.fsn,
                "basedOn": formatted_based_on,
                "definition": self.definition
            }
        else:
            # Formato PADRÃO (Simples)
            return {
                "sctid": self.sctid,
                "term": self.fsn,
                "type": self.semantic_tag
            }

@dataclass
class SemanticRule:
    raw_rule: AssociationRule
    normalized_consequents: List[ConceptNode]
    validation_status: str
    validation_reason: str
    
    def to_json(self):
        # Monta a string legível da regra original
        input_str = f"{', '.join(self.raw_rule.antecedents)} -> {', '.join(self.raw_rule.consequents)}"
        
        # Gera o grounding usando o método customizado de cada nó
        grounding_list = [node.to_output_format() for node in self.normalized_consequents]

        return {
            "evidence": {
                "input": input_str,
                "metrics": {
                    "lift": round(self.raw_rule.lift, 4), 
                    "conf": round(self.raw_rule.confidence, 4),
                    "supp": round(self.raw_rule.support, 4)
                }
            },
            "grounding": grounding_list,
            "status": self.validation_status,
            "note": self.validation_reason
        }

# ==============================================================================
# 3. LOADER INTELIGENTE (COM LÓGICA DE CUSTOMIZAÇÃO)
# ==============================================================================

class SnomedMapLoader:
    def __init__(self, user_map: Dict[str, str], atom_meta: Dict[str, dict]):
        self.user_map = user_map
        self.atom_meta = atom_meta
        self._custom_counter = 1
        self._cache = {}

    def _get_next_custom_id(self):
        cid = f"CUST_{self._custom_counter:03d}"
        self._custom_counter += 1
        return cid

    def _clean_term(self, raw_text: str) -> str:
        # Remove coisas como "MovementAcceleration [g]=" e deixa só "acc_baixa"
        if "=" in raw_text:
            return raw_text.split("=", 1)[1].strip()
        return raw_text.strip()

    def _resolve_atom_name(self, sctid: str) -> str:
        if sctid in self.atom_meta:
            return self.atom_meta[sctid]['term']
        return "Unknown Concept"

    def find_concept(self, raw_text: str) -> Optional[ConceptNode]:
        core_term = self._clean_term(raw_text)
        
        # 1. Busca no Mapa
        sctid_expr = self.user_map.get(core_term)
        
        # Fallback: Procura se a chave está contida na string
        if not sctid_expr:
            for k, v in self.user_map.items():
                if k in raw_text:
                    sctid_expr = v
                    core_term = k # Normaliza o nome para o termo mapeado
                    break
        
        if not sctid_expr:
            return None

        # Check Cache
        if sctid_expr in self._cache:
            return self._cache[sctid_expr]

        # 2. Analisa se é Composto (Custom) ou Simples
        if "+" in sctid_expr:
            # === LOGICA CUSTOM ===
            parts = sctid_expr.split("+")
            constituents = []
            def_parts = []
            
            for part_id in parts:
                meta = self.atom_meta.get(part_id, {"term": "Unknown", "def": ""})
                constituents.append({"id": part_id, "term": meta['term']})
                if meta['def']:
                    def_parts.append(meta['def'])
            
            # Gera definição composta
            full_def = f"{core_term}; Combinação de: {'; '.join(def_parts)}."
            
            node = ConceptNode(
                sctid=sctid_expr,
                fsn=core_term, # Ex: acc_baixa
                is_custom=True,
                custom_id=self._get_next_custom_id(),
                constituents=constituents,
                definition=full_def,
                semantic_tag="observable entity"
            )
        else:
            # === LOGICA SIMPLES ===
            meta = self.atom_meta.get(sctid_expr, {})
            term_display = meta.get('term', core_term)
            tag = "disorder" if "Fibrillation" in term_display else "finding"
            
            node = ConceptNode(
                sctid=sctid_expr,
                fsn=term_display,
                is_custom=False,
                semantic_tag=tag
            )

        self._cache[sctid_expr] = node
        return node

# ==============================================================================
# 4. PROCESSADOR E EXECUTOR
# ==============================================================================

class SemanticProcessor:
    def __init__(self, ontology: SnomedMapLoader):
        self.ontology = ontology

    def process_rule(self, rule: AssociationRule) -> SemanticRule:
        grounded_concepts = []
        missing = 0
        
        for cons in rule.consequents:
            concept = self.ontology.find_concept(cons)
            if concept:
                grounded_concepts.append(concept)
            else:
                missing += 1
        
        status = "VALID"
        note_parts = []
        if missing > 0:
            status = "WARNING"
            note_parts.append(f"Failed to ground {missing} terms.")
        
        if not note_parts:
            note_parts.append(f"Successfully grounded {len(grounded_concepts)} concept(s).")

        return SemanticRule(rule, grounded_concepts, status, " ".join(note_parts))

def generate_llm_payload(rules: List[SemanticRule]):
    # Cabeçalho fixo solicitado
    header = {
        "role": "system",
        "instruction": """
          Contexto: Analise de regras de associação de sensores IoT de saude.
          Objetivo: Explicar clinicamente os padroes encontrados.
          Ontologia: Os códigos 'sctid' referem-se ao SNOMED CT. Expressoes com '+' indicam pos-coordenacao (composicao).

          Instruções:
                 1. Analise o campo 'evidence' (metricas estatisticas).
                 2. Correlacione com o 'grounding' (significado clinico).
                 3. Identifique padrões de risco (ex: Fibrilacao Atrial associada a certas atividades).
        """
    }
    
    data_list = [r.to_json() for r in rules]
    
    return {**header, "data": data_list}

def frozenset_to_list(s):
    # Utilitário para limpar o formato do pandas frozenset
    if pd.isna(s): return []
    return re.findall(r"'(.*?)'", str(s))

# ==============================================================================
# EXECUÇÃO
# ==============================================================================
if __name__ == "__main__":
    # 1. Dados de Exemplo (Simulando o CSV)
    data = {
        'antecedents': [
            "frozenset({'MovementAcceleration [g]=acc_baixa'})", 
            "frozenset({'ActivityClass_mapped=activity_lying'})"
        ],
        'consequents': [
            "frozenset({'ArrhythmiaClass=AF (Atrial Fibrillation)'})",
            "frozenset({'MovementAcceleration [g]=acc_baixa'})" 
        ],
        'confidence': [0.5797, 0.88],
        'lift': [1.1153, 1.05],
        'support': [0.3091, 0.25]
    }
    df = pd.DataFrame(data)
    df['antecedents_list'] = df['antecedents'].apply(frozenset_to_list)
    df['consequents_list'] = df['consequents'].apply(frozenset_to_list)

    # 2. Inicialização
    # Passamos o mapa de IDs e o dicionário de definições
    loader = SnomedMapLoader(USER_SNOMED_MAP, ATOM_METADATA)
    processor = SemanticProcessor(loader)
    
    results = []

    # 3. Processamento
    for index, row in df.iterrows():
        rule = AssociationRule(
            antecedents=row['antecedents_list'],
            consequents=row['consequents_list'],
            confidence=row['confidence'],
            lift=row['lift'],
            support=row['support']
        )
        results.append(processor.process_rule(rule))

    # 4. Saída JSON
    final_payload = generate_llm_payload(results)
    
    print(json.dumps(final_payload, indent=2, ensure_ascii=False))